
SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for `OLO_PD_ORDEROLOPDORDER`
-- ----------------------------
DROP TABLE IF EXISTS `OLO_PD_ORDEROLOPDORDER`;
CREATE TABLE `OLO_PD_ORDEROLOPDORDER` (
 		`OLOPDORDER_ID` varchar(100) NOT NULL,
		`STATE` varchar(255) DEFAULT NULL COMMENT '状态',
		`SEALED` varchar(255) DEFAULT NULL COMMENT '封存商品 默认 0  不封存 1 封存',
		`CREATE_TIME` varchar(255) DEFAULT NULL COMMENT '创建时间',
		`USER_ID` varchar(255) DEFAULT NULL COMMENT '下单人员ID',
		`CREATION_PEOPLE_ID` varchar(255) DEFAULT NULL COMMENT '创建人ID',
		`UPDATE_TIME` varchar(255) DEFAULT NULL COMMENT '更新时间',
		`UPDATE_PEOPLE_ID` varchar(255) DEFAULT NULL COMMENT '更新人ID',
		`SPREAD1` varchar(255) DEFAULT NULL COMMENT 'Spread1',
		`SPREAD2` varchar(255) DEFAULT NULL COMMENT 'Spread2',
		`SPREAD3` varchar(255) DEFAULT NULL COMMENT 'Spread3',
		`SPREAD4` varchar(255) DEFAULT NULL COMMENT 'Spread4',
		`SPREAD5` varchar(255) DEFAULT NULL COMMENT 'Spread5',
  		PRIMARY KEY (`OLOPDORDER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
