
SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for `OLO_PD_SHOPPING_CARTOLOPDSHOPPINGCART`
-- ----------------------------
DROP TABLE IF EXISTS `OLO_PD_SHOPPING_CARTOLOPDSHOPPINGCART`;
CREATE TABLE `OLO_PD_SHOPPING_CARTOLOPDSHOPPINGCART` (
 		`OLOPDSHOPPINGCART_ID` varchar(100) NOT NULL,
		`USER_ID` varchar(255) DEFAULT NULL COMMENT '人员ID',
		`SKU_ID` varchar(255) DEFAULT NULL COMMENT '物品ID',
		`CODE` varchar(255) DEFAULT NULL COMMENT '商品编码',
		`TITLE` varchar(255) DEFAULT NULL COMMENT '商品名称',
		`NUMBER` varchar(255) DEFAULT NULL COMMENT '数量',
		`PRICE` varchar(255) DEFAULT NULL COMMENT '价格',
		`CREATE_TIME` varchar(255) DEFAULT NULL COMMENT '创建时间',
		`CREATION_PEOPLE_ID` varchar(255) DEFAULT NULL COMMENT '创建人ID',
		`UPDATE_TIME` varchar(255) DEFAULT NULL COMMENT '更新时间',
		`UPDATE_PEOPLE_ID` varchar(255) DEFAULT NULL COMMENT '更新人ID',
		`SPREAD1` varchar(255) DEFAULT NULL COMMENT 'Spread1',
		`SPREAD2` varchar(255) DEFAULT NULL COMMENT 'Spread2',
		`SPREAD3` varchar(255) DEFAULT NULL COMMENT 'Spread3',
		`SPREAD4` varchar(255) DEFAULT NULL COMMENT 'Spread4',
		`SPREAD5` varchar(255) DEFAULT NULL COMMENT 'Spread5',
  		PRIMARY KEY (`OLOPDSHOPPINGCART_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
